apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aischeduleddeployments.y5n.com
spec:
  group: y5n.com
  scope: Namespaced
  names:
    plural: aischeduleddeployments
    singular: aischeduleddeployment
    kind: AIScheduledDeployment
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              nodeSelectorAIModel:
                type: string
              minReadySeconds:
                type: integer
              paused:
                type: boolean
              progressDeadlineSeconds:
                type: integer
              replicas:
                type: integer
              revisionHistoryLimit:
                type: integer
              selector:
                type: string
              strategy:
                type: object
                properties:
                  rollingUpdate:
                    type: object
                    properties:
                      maxSurge:
                        x-kubernetes-int-or-string: true
                      maxUnavailable:
                        x-kubernetes-int-or-string: true
                  type:
                    type: string
              template:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      labels:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                  spec:
                    type: object
                    properties:
                      nodeSelector:
                        type: object
                        additionalProperties:
                          type: string
                      volumes:
                        type: string
                      containers:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            image:
                              type: string
                            ports:
                              type: array
                              items:
                                type: object
                                properties:
                                  containerPort:
                                    type: integer
                                  hostIP:
                                    type: string
                                  hostPort:
                                    type: integer
                                  name:
                                    type: string
    selectableFields:
    - jsonPath: .spec.nodeSelectorAIModel
    additionalPrinterColumns:
    - jsonPath: .spec.nodeSelectorAIModel
      name: NodeSelectorAIModel
      type: string
    - jsonPath: .spec.size
      name: Size
      type: string

